import React, { useState } from "react";
import Head from "next/head";
import Styles from "../styles/Crud.module.css";
import axios, { AxiosError, AxiosInstance, AxiosRequestConfig } from "axios";

export async function getStaticPaths() {
  const res = await axios.get(
    `https://611a-2405-201-e026-60d7-40ef-22c0-dd46-d5a7.in.ngrok.io/api/login-details`
  );
  const customerData = await res.data;
  const custData = customerData.data.map((i) => {
    return { params: { id: i.id.toString() } };
    /*  setData( custData.data.data.map(row =>({FirstName:row.FirstName,LastName:row.LastName })) ); */
  });
  console.log("result---->", custData);
  return {
    paths: custData,
    fallback: false, // can also be true or 'blocking'
  };
}

export async function getStaticProps({ params }) {
  const getId = await fetch(
    `https://611a-2405-201-e026-60d7-40ef-22c0-dd46-d5a7.in.ngrok.io/api/login-details/${params.id}`
  );

  console.log("id-getstaticprops---->", getId);

  return {
    props: {
      result: await getId.json()
    },
   
    // will be passed to the page component as props
  };
}

export default function Update(props) {

  const [FirstName, setFirstName] = useState(
    props.result.data.attributes.FirstName
  );
  const [LastName, setLastName] = useState(
    props.result.data.attributes.LastName
  );

  const UpdateData = async () => {
    console.log("----firstName-",  props.result.data.attributes.FirstName);
    console.log("----lastName", props.result.data.attributes.LastName);
    console.log("props.result.data.id--->",props.result.data.id);

    const pos = await fetch(
      `http://localhost:9000/store/products/${props.result.data.id}`,
      {
        method: "PUT",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ data: { FirstName, LastName } }),
      }
    );

    setFirstName("");
    setLastName("");

  };

  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossorigin="anonymous"
        ></link>
        <script
          src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
          integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
          crossorigin="anonymous"
        ></script>
        <script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
          integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
          crossorigin="anonymous"
        ></script>
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossorigin
        ></link>
        <link
          href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;500;600;700;800&family=Oswald&display=swap"
          rel="stylesheet"
        ></link>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
        ></link>
      </Head>
      <div className={`${Styles.container} `}>
        <div className="justify-content-center d-flex align-items-center">
          <div className={`${Styles.cardLogin} shadow `}>
            <div
              className={`${Styles.cardBoxe} justify-content-center align-items-center  `}
            >
              <input
                className={`${Styles.cardInp} w-100 mt-2`}
                type="text"
                placeholder="First Name"
                value={FirstName}
                onChange={(e) => {
                  setFirstName(e.target.value);
                }}
              />
              <input
                className={`${Styles.cardInp} w-100 mt-4 `}
                type="text"
                placeholder="Last Name"
                value={LastName}
                onChange={(e) => {
                  setLastName(e.target.value);
                }}
              />
              <div className="mt-4 justify-content-center align-items-center d-flex">
                <button
                  className={`${Styles.cardbtn} w-100 mt-4 `}
                  onClick={UpdateData}
                >
                  Submit
                </button>
              </div>
            </div>
          </div>
        </div>
        <div className="mt-4 justify-content-center align-items-center d-flex">
          <button className={`${Styles.cardBtntwo}  mt-4 shadow `}>
            <a href="./Tabless">View Table</a>
          </button>
        </div>
      </div>
    </>
  );
}
