import React, { useState } from "react";
import Head from "next/head";
import Styles from "../styles/Crud.module.css";
import axios, { AxiosError, AxiosInstance, AxiosRequestConfig } from "axios";

export default function Crud() {
  const [FirstName, setFirstName] = useState("");
  const [LastName, setLastName] = useState("");

  const createLogin = async () => {
    console.log("----firstName-", FirstName);
    console.log("----lastName", LastName);

    const result = await fetch(
      `https://611a-2405-201-e026-60d7-40ef-22c0-dd46-d5a7.in.ngrok.io/api/login-details`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ data: { FirstName, LastName } }),
      }
    );
    console.log("result", result);
    setFirstName("");
    setLastName("");
  };

  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossorigin="anonymous"
        ></link>
        <script
          src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
          integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
          crossorigin="anonymous"
        ></script>
        <script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
          integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
          crossorigin="anonymous"
        ></script>
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossorigin
        ></link>
        <link
          href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;500;600;700;800&family=Oswald&display=swap"
          rel="stylesheet"
        ></link>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
        ></link>
      </Head>
      <div className={`${Styles.container} `}>
        <div className="justify-content-center d-flex align-items-center">
          <div className={`${Styles.cardLogin} shadow `}>
            <div
              className={`${Styles.cardBoxe} justify-content-center align-items-center  `}
            >
              <input
                className={`${Styles.cardInp} w-100 mt-2`}
                type="text"
                placeholder="First Name"
                value={FirstName}
                onChange={(e) => {
                  setFirstName(e.target.value);
                }}
              />
              <input
                 value={LastName}
                className={`${Styles.cardInp} w-100 mt-4 `}
                type="text"
                placeholder="Last Name"
                onChange={(e) => {
                  setLastName(e.target.value);
                }}
              />
              <div className="mt-4 justify-content-center align-items-center d-flex">
                <button
                  className={`${Styles.cardbtn} w-100 mt-4 `}
                  onClick={() => createLogin()}
                >
                  Submit
                </button>
              </div>
            </div>
          </div>
        </div>
        <div className="mt-4 justify-content-center align-items-center d-flex">
          <button className={`${Styles.cardBtntwo}  mt-4 shadow `}>
            <a href="./Tabless">View Table</a>
          </button>
        </div>
      </div>
    </>
  );
}
