import styles from "../styles/Home.module.css";
import Head from "next/head";
import Image from "next/image";
import { Row, Col } from "antd";
import "antd/dist/antd.css";
import Link from "next/link";
import Calcultor from "./Calculator";
import Display from "./Display";
import DisCollection from "./DisCollection";
import ProductType from "./ProductType";
import Calc from "../pages/calculator/Calc";

export default function Home() {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossorigin="anonymous"
        ></link>
        <script
          src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
          integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
          crossorigin="anonymous"
        ></script>
        <script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
          integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
          crossorigin="anonymous"
        ></script>
        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossorigin
        ></link>
        <link
          href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;500;600;700;800&family=Oswald&display=swap"
          rel="stylesheet"
        ></link>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
        ></link>
      </Head>
      <div className={`${styles.container} shadow `}>
        <div className="container h-100">
          <Row className="w-100 h-100">
            <Col xs={16} sm={12} md={12} lg={8} xl={8}>
              <div className="w-100 h-100 d-flex justify-content-start align-items-center ">
                <div className={`${styles.cards_logo} ms-4 `}>
                  <Image src="/isdb.png" width={"34px"} height={"43px"} />
                </div>
                <div
                  className="ms-4"
                  style={{
                    height: "50px",
                    width: "1px",
                    backgroundColor: "#C4C4C4",
                  }}
                ></div>
                <div className={`${styles.card_head}  ms-4 `}>
                  Resemble Systems{" "}
                </div>
              </div>
            </Col>
            <Col xs={0} sm={0} md={0} lg={16} xl={16}>
              <div className=" w-100 h-100  d-flex justify-content-end align-items-center  ">
                <div className={`${styles.card_head_home} ms-2`}>Home</div>
                <div className={`${styles.card_head_home} ms-4 `}>
                  <Link href="/calculator">
                    <a>Calculator</a>
                  </Link>
                </div>
                <div className={`${styles.card_head_home} ms-4`}>
                  <Link href="/tictactoe">
                    <a>TicTacToe</a>
                  </Link>
                </div>
                <div className={`${styles.card_head_home} ms-4`}>
                  <Link href="/Crud">
                    <a>CRUD</a>
                  </Link>
                </div>
                <div className={`${styles.card_head_home} ms-4 `}>
                  <Link href="/Tabless">
                    <a>Tables</a>
                  </Link>
                </div>
                <div className={`${styles.card_head_home} ms-4`}>
                  <Link href="/Display">
                    <a>Products</a>
                  </Link>
                </div>
                <div className={`${styles.card_head_home} ms-4`}>
                  <Link href="/DisCollection">
                    <a>Collect</a>
                  </Link>
                </div>
                <div className={`${styles.card_head_home} ms-4`}>
                  <Link href="/ProductType">
                    <a>PType</a>
                  </Link>
                </div>
                <div className={`${styles.card_head_home} ms-4`}>
                  <Link
                    href="calculator/Calc">
                    <a>Calc</a>
                  </Link>
                </div>
                {/* <div className={`${styles.card_head_menuitems} ms-4`}>Find</div>
                <div className={`${styles.card_head_menuitems} ms-4 `}>
                  Chat
                </div> */}
                <div
                  className={`${styles.card_head_image} ms-4 rounded-circle overflow-hidden`}
                >
                  <Image src="/jhon.jpg" width={"50px"} height={"50px"} />
                </div>
                <div className={`${styles.card_head_menuitems} ms-4 me-5`}>
                  John Doe
                </div>
              </div>
            </Col>
            {/* <Col xs={8} sm={12} md={12} lg={0} xl={0}>
              <div className="w-100 justify-content-end d-flex align-items-center h-100">
                <Image
                  src="/Icon material-menu@2x.png"
                  width={"27px"}
                  height={"18px"}
                />
              </div>
            </Col> */}
          </Row>
        </div>
      </div>
    </>
  );
}

//<Link href="/calculator">
//<a>Calculator</a>
//</Link>
